a. Using NumPy create random vector of size 15 having only Integers in the Range 1-20.
1. Reshape the array to 3 by 5
2. Print array shape.
3. Replace the max in each row by 0

Create a 2-dimensional array of size 4 x 3 (composed of 4-byte integer elements), also print the shape, type and data type of the array.

In [11]:
import numpy as np

# Random Vector and Reshaping
# Create a random vector of size 15 with integers in the range 1 to 20
random_vector = np.random.randint(1, 21, size=15)
print("Random Vector:\n", random_vector)

# 1. Reshape the array to 3 by 5
reshaped_array = random_vector.reshape(3, 5)
print("\nReshaped Array (3x5):\n", reshaped_array)

# 2. Print array shape
print("\nShape of the Reshaped Array:", reshaped_array.shape)

# 3. Replace the max in each row by 0
for i in range(reshaped_array.shape[0]):
    reshaped_array[i, reshaped_array[i].argmax()] = 0

print("\nArray after Replacing Max in Each Row by 0:\n", reshaped_array)

# Create a 2D Array of Size 4x3 with 4-byte Integers
# Create a 2-dimensional array of size 4x3 with 4-byte integer elements
array_4x3 = np.zeros((4, 3), dtype=np.int32)

print("\n2D Array of Size 4x3:\n", array_4x3)
print("\nShape of the Array:", array_4x3.shape)
print("\nType of the Array:", type(array_4x3))
print("\nData Type of Array Elements:", array_4x3.dtype)


Random Vector:
 [ 1 20 14  1 13  6 20 11 19 18  9 11  4  6 13]

Reshaped Array (3x5):
 [[ 1 20 14  1 13]
 [ 6 20 11 19 18]
 [ 9 11  4  6 13]]

Shape of the Reshaped Array: (3, 5)

Array after Replacing Max in Each Row by 0:
 [[ 1  0 14  1 13]
 [ 6  0 11 19 18]
 [ 9 11  4  6  0]]

2D Array of Size 4x3:
 [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]

Shape of the Array: (4, 3)

Type of the Array: <class 'numpy.ndarray'>

Data Type of Array Elements: int32


b. Write a program to compute the eigenvalues and right eigenvectors of a given square array given below:

[[ 3 -2]

[1 0]]

In [2]:
import numpy as np

# Define the matrix
matrix = np.array([[3, -2], [1, 0]])

# Compute the eigenvalues and right eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

# Print the eigenvalues and eigenvectors
print("Matrix:\n", matrix)
print("\nEigenvalues:\n", eigenvalues)
print("\nRight Eigenvectors:\n", eigenvectors)

Matrix:
 [[ 3 -2]
 [ 1  0]]

Eigenvalues:
 [2. 1.]

Right Eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


c. Compute the sum of the diagonal element of a given array.

[[0 1 2]

[3 4 5]]

In [9]:
import numpy as np

# Define the array
array = np.array([[0, 1, 2],
                  [3, 4, 5]])

# Compute the sum of diagonal elements
diagonal_sum = np.trace(array)

# Print the array and sum
print("Array:\n", array)
print("\nSum of diagonal elements:", diagonal_sum)


Array:
 [[0 1 2]
 [3 4 5]]

Sum of diagonal elements: 4


d. Write a NumPy program to create a new shape to an array without changing its data.

Reshape 3x2:

[[1 2]

[3 4]

[5 6]

Reshape 2x3:

[[1 2 3]

[4 5 6]]

In [12]:
import numpy as np

# Define the arrays
array1 = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])

array2 = np.array([[1, 2, 3],
                   [4, 5, 6]])

# Reshape array1 to 3x2
reshaped_array1 = array1.reshape(3, 2)

# Reshape array2 to 2x3
reshaped_array2 = array2.reshape(2, 3)

# Print the reshaped arrays
print("Reshaped array1 (3x2):")
print(reshaped_array1)

print("\nReshaped array2 (2x3):")
print(reshaped_array2)


Reshaped array1 (3x2):
[[1 2]
 [3 4]
 [5 6]]

Reshaped array2 (2x3):
[[1 2 3]
 [4 5 6]]
